---
- hosts: db
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Install the latest version of Apache
    yum:
      name: apache2
      state: latest
  - name: Start service httpd
    service:
      name: apache2
      state: started
  - name: Copy file
    copy:
      src: index.html
      dest: /var/www/html
      mode: '777'
