---
- hosts: db
  become: True
  tasks:
    - name: Install the latest version of Apache
    apt:
      name: apache2
      state: latest
  - name: Start service httpd
    service:
      name: apache2
      state: started

    - name: Deploy static website
      copy:
         src: /var/lib/ubuntu/webapp.war
         dest: /var/www/html/index.html
         mode: '777'
