---
- hosts: all
  tasks:
    - maven_artifact:
        group_id: com.devops4solutions
        artifact_id: LoginWebApp
        repository_url: 'http://44.202.34.209:8081/repository/maven-releases/'
        username: admin
        password: admin
        dest: /opt
