---
- hosts: db
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Install the latest version of Apache
    yum:
      name: apache2
      state: latest
  - name: Start service httpd
    service:
      name: apache2
      state: started
  - name: Copy file
    copy:
      src: /var/lib/jenkins/workspace/ansible-project/target/LoginWebApp-1.war
      dest: /var/www/html/index.html
      mode: '777'
